sonar.projectKey=AutoRepairOrg_AutoRepairShop-OsService
sonar.organization=autorepairorg
sonar.projectName=AutoRepairShop-OsService

sonar.sources=src
sonar.tests=tests
sonar.language=cs
sonar.dotnet.excludeTestProjects=true

sonar.cs.opencover.reportsPaths=coverage/**/coverage.opencover.xml
